#!/usr/bin/env bash
# script that configures an Ubuntu server
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root using sudo."
    exit 1
fi
cp /etc/hosts /etc/hosts.bak
sed -i '/\slocalhost$/d' /etc/hosts
sed -i '/\sfacebook\.com$/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
echo "Updated /etc/hosts:"
cat /etc/hosts
